// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGgVoC8tUyF8w7TFeHX_8ck-FwZQlFhmo',
    appId: '1:201650157860:web:60cbb40dcda68e1092dbb1',
    messagingSenderId: '201650157860',
    projectId: 'farm-manager-ha0ij2',
    authDomain: 'farm-manager-ha0ij2.firebaseapp.com',
    storageBucket: 'farm-manager-ha0ij2.firebasestorage.app',
    measurementId: 'G-9L14R4GCEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmGpPCiWpzr3PLEXGqh2zKbt_bMGHP-ps',
    appId: '1:201650157860:android:18f2b0baed0eefd192dbb1',
    messagingSenderId: '201650157860',
    projectId: 'farm-manager-ha0ij2',
    storageBucket: 'farm-manager-ha0ij2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBeLVd308UK5TiWhY9gvbXZUswvoF7FxQ',
    appId: '1:201650157860:ios:454c241242aa90ae92dbb1',
    messagingSenderId: '201650157860',
    projectId: 'farm-manager-ha0ij2',
    storageBucket: 'farm-manager-ha0ij2.firebasestorage.app',
    androidClientId: '201650157860-gvmc0pvejules7atq2k9bjp4ik0k8863.apps.googleusercontent.com',
    iosClientId: '201650157860-v8km9377vc8eg7r4c8dlf2ess86s2hlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBeLVd308UK5TiWhY9gvbXZUswvoF7FxQ',
    appId: '1:201650157860:ios:454c241242aa90ae92dbb1',
    messagingSenderId: '201650157860',
    projectId: 'farm-manager-ha0ij2',
    storageBucket: 'farm-manager-ha0ij2.firebasestorage.app',
    androidClientId: '201650157860-gvmc0pvejules7atq2k9bjp4ik0k8863.apps.googleusercontent.com',
    iosClientId: '201650157860-v8km9377vc8eg7r4c8dlf2ess86s2hlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGgVoC8tUyF8w7TFeHX_8ck-FwZQlFhmo',
    appId: '1:201650157860:web:4857b1adf501380a92dbb1',
    messagingSenderId: '201650157860',
    projectId: 'farm-manager-ha0ij2',
    authDomain: 'farm-manager-ha0ij2.firebaseapp.com',
    storageBucket: 'farm-manager-ha0ij2.firebasestorage.app',
    measurementId: 'G-RGG770YLPY',
  );

}